#!/usr/bin/env bash

# List files in IPA with size

set -e

# Show usage and quit
usage () {
    echo "Usage: ls_ipa [-s] /path/to/ipa"
    return 1
}

prepare () {
    ipa=$1

    # Create temp working dir
    WS=$(mktemp -t ck-ios-build-scripts)
    [ -d "$WS" ] || rm -rf "$WS"
    mkdir "$WS"

    # Unzip ipa
    unzip -q "$ipa" -d "$WS"

    # Get it done
    cd "$WS/Payload/"
}

ls_ipa_by_size () {
    find ./*.app -depth 1 -print0 | xargs -0 -I{} du -s {} | sort -rn | cut -f2 | xargs -I{} du -sh {}
}

ls_ipa_by_name () {
    find ./*.app -depth 1 -print0 | xargs -0 -I{} du -hs {}
}

main () {
    while getopts :sh opt; do
        case $opt in
        s)
            ls_by_size=1
            ;;
        \?)
            usage
            ;;
        esac
    done

    shift $((OPTIND-1))

    if [ ! -f "$1" ];
    then
        usage
    fi

    prepare "$1"

    if [ -n "$ls_by_size" ];
    then
        ls_ipa_by_size
    else
        ls_ipa_by_name
    fi
}

main "$@"
