#!/usr/bin/env bash

update_version() {
    local version=$1

    if ! echo "$version" | grep -q -E '^[0-9]+(\.[0-9]+)+$'
    then
        echo "error: Invalid version specified"
        exit 1
    fi

    xcrun agvtool new-marketing-version "$version"
}

update_version "$@"
